# Generated by Django 4.1.2 on 2022-10-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safedelete', '__first__'),
        ('YouOnline_app', '0004_remove_posts_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('softdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='safedelete.softdeletemodel')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('safedelete.softdeletemodel',),
        ),
    ]
