# Generated by Django 4.1.2 on 2022-10-28 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouOnline_app', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
