# Generated by Django 4.1.2 on 2022-10-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouOnline_app', '0007_posts1'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='', verbose_name='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='posts',
        ),
        migrations.DeleteModel(
            name='posts1',
        ),
    ]
