# Generated by Django 4.1.2 on 2022-10-29 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YouOnline_app', '0008_post_delete_posts_delete_posts1'),
    ]

    operations = [
        migrations.CreateModel(
            name='youonline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('text_post', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='', verbose_name='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
